<?php
require_once '../includes/auth.php'; require_once '../includes/functions.php';
requireStudent(); $user=currentUser();
$filters=['search'=>$_GET['search']??'', 'dept'=>$_GET['dept']??'', 'available'=>$_GET['available']??'']; $courses=getCourses($filters);
$pageTitle='Course Catalog'; $activePage='courses'; $sidebarRole='student';
require_once '../includes/header.php'; require_once '../includes/sidebar.php';
?>
<div class="p-8 max-w-6xl mx-auto"><div class="mb-6"><h2 class="text-2xl font-semibold text-on-surface mb-1">Available Courses</h2><p class="text-sm text-on-surface-variant">Courses are loaded directly from the database.</p></div>
<form method="GET" class="card mb-6 p-5"><div class="flex flex-col md:flex-row gap-4"><input name="search" value="<?= e($filters['search']) ?>" class="form-input" placeholder="Search by course title, code, or instructor"><select name="dept" class="form-input max-w-xs"><option value="">All Departments</option><?php foreach(['Computer Science','Business Administration','Liberal Arts','Mathematics','Engineering','Natural Sciences'] as $d): ?><option <?= $filters['dept']===$d?'selected':'' ?>><?= e($d) ?></option><?php endforeach; ?></select><select name="available" class="form-input max-w-xs"><option value="">All Status</option><option value="available" <?= $filters['available']==='available'?'selected':'' ?>>Available</option><option value="full" <?= $filters['available']==='full'?'selected':'' ?>>Full</option></select><button class="btn-primary" type="submit">Filter</button></div></form>
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"><?php foreach($courses as $c): $isFull=(int)$c['available_seats']<=0 || $c['status']==='full'; ?><div class="course-card"><div class="flex justify-between gap-2 mb-3"><span class="font-bold text-primary"><?= e($c['course_code']) ?></span><span class="<?= $isFull?'badge-full':'badge-available' ?>"><?= $isFull?'Full':'Available' ?></span></div><h3 class="text-lg font-semibold mb-2"><?= e($c['course_title']) ?></h3><p class="text-sm text-on-surface-variant flex-grow"><?= e($c['description']) ?></p><div class="text-xs text-on-surface-variant mt-4 space-y-1"><p><strong>Instructor:</strong> <?= e($c['instructor']) ?></p><p><strong>Credits:</strong> <?= (int)$c['credit_hours'] ?></p><p><strong>Schedule:</strong> <?= e($c['schedule_day']) ?>, <?= e($c['schedule_time']) ?></p><p><strong>Seats:</strong> <?= (int)$c['available_seats'] ?> / <?= (int)$c['capacity'] ?></p></div><button class="btn-primary w-full justify-center mt-5" <?= $isFull?'disabled style="opacity:.5;cursor:not-allowed"':'' ?> onclick="enrollCourse(<?= (int)$c['course_id'] ?>)">Register</button></div><?php endforeach; ?></div></div>
<?php require_once '../includes/footer.php'; ?>
