<?php
require_once '../includes/auth.php'; require_once '../includes/functions.php';
requireStudent(); $user=currentUser(); $stats=getStudentStats((int)$user['user_id']); $myCourses=getStudentCourses((int)$user['user_id']);
$pageTitle='Student Dashboard'; $activePage='dashboard'; $sidebarRole='student';
require_once '../includes/header.php'; require_once '../includes/sidebar.php';
?>
<div class="p-8 max-w-6xl mx-auto">
  <div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8"><div><h2 class="text-3xl font-semibold text-on-surface">Welcome back, <?= e(explode(' ', $user['full_name'])[0]) ?></h2><p class="text-sm text-on-surface-variant mt-1">Here is your live academic overview.</p></div><a href="<?= url('/student/courses.php') ?>" class="btn-primary"><span class="ms" style="font-size:18px">search</span>Browse Courses</a></div>
  <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8"><div class="stat-card"><p class="text-xs font-semibold tracking-wider text-on-surface-variant uppercase mb-1">Total Enrolled Credits</p><p class="text-5xl font-bold text-on-surface"><?= (int)$stats['total_credits'] ?></p></div><div class="stat-card"><p class="text-xs font-semibold tracking-wider text-on-surface-variant uppercase mb-1">Courses Registered</p><p class="text-5xl font-bold text-on-surface"><?= (int)$stats['registered_courses'] ?></p></div><div class="stat-card"><p class="text-xs font-semibold tracking-wider text-on-surface-variant uppercase mb-1">Available Courses</p><p class="text-5xl font-bold text-on-surface"><?= (int)$stats['available_courses'] ?></p></div></div>
  <div class="grid grid-cols-1 lg:grid-cols-3 gap-6"><div class="lg:col-span-2 card"><h3 class="font-semibold text-on-surface mb-4">Current Registrations</h3><?php if (!$myCourses): ?><p class="text-sm text-on-surface-variant">You are not registered for courses yet.</p><?php else: ?><div class="space-y-3"><?php foreach ($myCourses as $c): ?><div class="border border-border rounded-lg p-4 flex justify-between gap-4"><div><h4 class="font-semibold"><?= e($c['course_code']) ?> - <?= e($c['course_title']) ?></h4><p class="text-sm text-on-surface-variant"><?= e($c['instructor']) ?> · <?= e($c['schedule_day']) ?> · <?= e($c['schedule_time']) ?></p></div><button class="btn-danger" onclick="dropCourse(<?= (int)$c['course_id'] ?>)">Drop</button></div><?php endforeach; ?></div><?php endif; ?></div><div class="card text-center"><div class="w-20 h-20 rounded-full bg-secondary-container text-on-secondary-container flex items-center justify-center text-2xl font-bold mx-auto mb-4"><?= e(getInitials($user['full_name'])) ?></div><h3 class="font-semibold text-on-surface"><?= e($user['full_name']) ?></h3><p class="text-xs text-on-surface-variant mb-4"><?= e($user['program'] ?? '') ?> · Year <?= e($user['year_level'] ?? '') ?></p><a href="<?= url('/student/profile.php') ?>" class="btn-secondary w-full justify-center text-xs"><span class="ms" style="font-size:16px">person</span>View Profile</a></div></div>
</div>
<?php require_once '../includes/footer.php'; ?>
